#Robocode Compiler Properties
#Wed Apr 15 10:07:27 JST 2026
compiler.binary=
compiler.classpath=-classpath libs\\robocode.jar;C\:\\Users\\kagol\\GitHub-Clones\\Robocode\\env\\robots
compiler.options=
robocode.version=1.10.0
