#Robocode Properties
#Wed Apr 15 17:15:23 JST 2026
robocode.battle.default.battlefieldHeight=1200
robocode.battle.default.battlefieldWidth=1200
robocode.battle.default.gunCoolingRate=0.1
robocode.battle.default.hideEnemyNames=false
robocode.battle.default.inactivityTime=450
robocode.battle.default.numberOfBattles=100
robocode.battle.default.sentryBorderSize=100
robocode.cpu.constant=5738908
robocode.options.battle.desiredTPS=10000
robocode.options.development.path=./benchies,../Project/bin
robocode.options.rendering.antialiasing=0
robocode.options.rendering.method=0
robocode.options.rendering.text.antialiasing=0
robocode.version.lastrun=1.10.0
robocode.versionchecked=04/13/2026 19\:04\:26
