#Robocode window sizes
#Wed Apr 15 17:15:22 JST 2026
net.sf.robocode.ui.dialog.ConsoleDialog=390,159,500,400
net.sf.robocode.ui.dialog.NewBattleDialog=214,35,850,650
net.sf.robocode.ui.dialog.RobocodeFrame=0,0,927,701
net.sf.robocode.ui.editor.RobocodeEditor=258,54,764,611
